Specify CMAKE_OSX_DEPLOYMENT_TARGET when building llvm (#285)
The version 11.0 is chosen because Apple seems providing
support for two previous releases.
(As of writing this, the latest is 13.)

REVISIT: as we don't need any brand-new OS features, it
might make more sense to specify even older version.

This might explain the following error i've seen with wasi-sdk-17.0
release binary on macos-11.0:
```
    Run Build Command(s):/usr/bin/make -f Makefile cmTC_254ef/fast && /Applications/Xcode_13.2.1.app/Contents/Developer/usr/bin/make  -f CMakeFiles/cmTC_254ef.dir/build.make CMakeFiles/cmTC_254ef.dir/build
    Building C object CMakeFiles/cmTC_254ef.dir/testCCompiler.c.obj
    /Users/runner/work/toywasm/toywasm/.wasi-sdk-17.0/bin/clang    -o CMakeFiles/cmTC_254ef.dir/testCCompiler.c.obj -c /Users/runner/work/toywasm/toywasm/build.wasm/CMakeFiles/CMakeScratch/TryCompile-aWXHXM/testCCompiler.c
    dyld: Symbol not found: __ZTTNSt3__114basic_ifstreamIcNS_11char_traitsIcEEEE
      Referenced from: /Users/runner/work/toywasm/toywasm/.wasi-sdk-17.0/bin/clang (which was built for Mac OS X 12.0)
      Expected in: /usr/lib/libc++.1.dylib
     in /Users/runner/work/toywasm/toywasm/.wasi-sdk-17.0/bin/clang
    make[1]: *** [CMakeFiles/cmTC_254ef.dir/testCCompiler.c.obj] Abort trap: 6
    make: *** [cmTC_254ef/fast] Error 2
```

References:
https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_DEPLOYMENT_TARGET.html