GHA: use macos-11 runner
According to the following github document,
macos-latest is either macos-11 or macos-12 at this point.

https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

It's better for us to use a consistent version to build.

This might explain the following error i've seen with wasi-sdk-17.0
release binary on macos-11.0:

```
    Run Build Command(s):/usr/bin/make -f Makefile cmTC_254ef/fast && /Applications/Xcode_13.2.1.app/Contents/Developer/usr/bin/make  -f CMakeFiles/cmTC_254ef.dir/build.make CMakeFiles/cmTC_254ef.dir/build
    Building C object CMakeFiles/cmTC_254ef.dir/testCCompiler.c.obj
    /Users/runner/work/toywasm/toywasm/.wasi-sdk-17.0/bin/clang    -o CMakeFiles/cmTC_254ef.dir/testCCompiler.c.obj -c /Users/runner/work/toywasm/toywasm/build.wasm/CMakeFiles/CMakeScratch/TryCompile-aWXHXM/testCCompiler.c
    dyld: Symbol not found: __ZTTNSt3__114basic_ifstreamIcNS_11char_traitsIcEEEE
      Referenced from: /Users/runner/work/toywasm/toywasm/.wasi-sdk-17.0/bin/clang (which was built for Mac OS X 12.0)
      Expected in: /usr/lib/libc++.1.dylib
     in /Users/runner/work/toywasm/toywasm/.wasi-sdk-17.0/bin/clang
    make[1]: *** [CMakeFiles/cmTC_254ef.dir/testCCompiler.c.obj] Abort trap: 6
    make: *** [cmTC_254ef/fast] Error 2
```